# Generated by Django 4.2.5 on 2023-09-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_fieldrule_scenario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
