# Generated by Django 4.2.5 on 2023-09-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_application_medicals_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Policy',
        ),
    ]
