# Generated by Django 4.2.5 on 2023-09-05 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_application_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
